### PR TITLE
#47 and #48 Playlist Enhancments

### PR DESCRIPTION
**Pull request by MMEnter**
Added Duration to Playlist.
Added Delete From Playlist Button to Playlist in Small and Medium VisualState.

### CODE REVIEW

**Review by deltakosh — COMMENTED** [review]
Did you tested it on the smallest mobile screen size

**Comment by MMEnter** [comment]
I am not sure. I have a Lumia 830 it has a 1280 by 720 resolution at 4'', it reports a 640 by 360 screen, getting the small VisualState. I test every build on that.

**Comment by deltakosh** [comment]
Do you mind testing with the emulators?

**Comment by MMEnter** [comment]
I have to install them first. I only have a cute 128GB SSD trying to run VS :D

**Comment by deltakosh** [comment]
:D

**Comment by MMEnter** [comment]
wvga 4 512mb

**Comment by MMEnter** [comment]
That's the WVGA 4'' 512MB Emulator screen.

**Comment by deltakosh** [comment]
Perfect!

**Pull request merged**
