### PR TITLE
Added Car mode with correct Style behavior #2 

### PR DESCRIPTION
**Pull request by MMEnter**
Added Car Mode by creating a new Visual State and resizing the Buttons and increas the margine between them.
Added Style to match the existing buttons behavior.

### CODE REVIEW

**Comment by deltakosh** [comment]
Cannot merge :( there is a conflict

**Comment by deltakosh** [comment]
This is far better :)
But the size when not in car mode is bigger than before and I would like to keep it like it was.

The car button may need some margins as well ;)

**Comment by MMEnter** [comment]
Yes, I tried to find the right size but couldn't find the code. What font size where the buttons before?

**Comment by deltakosh** [comment]
They were using symbol (I think you can pick the font size but using the live debugger)

**Comment by MMEnter** [comment]
I will try to match it better. I have a margin of 12  on the left side, should I do the same on top?

**Comment by deltakosh** [comment]
Should work:)

**Comment by MMEnter** [comment]
I added a old button back and reduced the font size of the new button until they where the same size, the magic number should be 20 (from 24), the 1.0x was way to big and had to be changed to 15. After I added the 12 point Top Margin to the Car and street Button the top row looked to big. I increased the buttons RowSpan to keep that row small.

Let me know if I need to change anything else.

**Comment by deltakosh** [comment]
Perfect Thanks!!

**Pull request merged**
